# This is a basic workflow to help you get started with Actions

name: CI
# Controls when the action will run. 
on: [push, pull_request]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Upload nested folder
      - name: Archive src folder
        uses: actions/upload-artifact@v2
        with:
          name: nested
          path: src/nested

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo 'ref: ' ${{ github.ref }} 
          echo "headref: " ${{ github.head_ref }}
          echo "baseref: "${{ github.base_ref }}
  test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dont'
    needs: build
    steps:
      - name: Don't run This
        run: docker image ls
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.base_ref == 'main'
    needs: build
    steps:
      - uses: actions/checkout@v2
      # Download artefacts
      - name: Upload src contens
        uses: actions/download-artifact@v2
        with:
          name: nested
          path: target/nested
      - name: show contents
        run: tree
      - name: read target file
        run: cat target/1.txt  
